name: Deploy Workflow
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest code
      - name: 🚚 Get latest code
        uses: actions/checkout@v3  # Ensure this is up-to-date

      # Setup Node.js
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.0'

      # Install dependencies and build the project
      - name: 🔨 Build Project
        run: |
          echo "Before npm install - Current Directory: $(pwd)"
          ls -la
          npm install
          npm run build

      # Deploy to FTP server
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          exclude: "./assets/**"
