name: Deploy Workflow
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20.5.0'

    - name: 🔨 Build Project
      run: |
        echo "Before npm install - Current Directory: $(pwd)"
        ls -la
        npm install
        npm run build

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        exclude: "./assets/**"
